### ISSUE TITLE
Implement the `mint_handle` function

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#15]
The `mint_handle` function mints a new karst handle to a profile address.

Takes in the local name, validates it and ties it to the profile address. Here are some resources to help you with implementation:
- [Lens implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/LensHandles.sol)
- [Handle Documentation](https://docs.lens.xyz/docs/handle)

you are expected to:
- Implement the `mint_handle` external and `_mint_handle` private functions respectively
- write the associated test for the implemented function

you are not expected to:
- implement the `_validate_local_name` function, but ensure to call it with the right variable passed in. will be implemented in another issue.

Note that:
- your implementation, doesn't need to be an exact copy of lens implementation. Be flexible, and properly comment your codes.
- Ask questions in the working group, if lost or unsure of anything.

**Comment by kateberryd** [comment]
Hi @Darlington02 I would like to work on this
