### ISSUE TITLE
implement the `burn_handle` function

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#16]
The `burn_handle` function burns a karst handle token and removes it from associated mappings.

Here are some resources to help you with implementation:

[Lens implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/LensHandles.sol#L121)
[Handle Documentation](https://docs.lens.xyz/docs/handle)

you are expected to:

- Implement the `burn_handle external` function.
- write the associated test for the implemented function

Note that:

- your implementation, doesn't need to be an exact copy of lens implementation. Be flexible, and properly comment your codes.
- Ask questions in the working group, if lost or unsure of anything.

**Comment by Oshioke-Salaki** [comment]
Hello I’d love to handle this @Darlington02

**Comment by codeWhizperer** [comment]
GM @Oshioke-Salaki , any update on this?

**Comment by Oshioke-Salaki** [comment]
Hello I am still working on it. Please can I have the telegram group link to ask some questions.

**Comment by Darlington02** [comment]
https://t.me/+DFfuHjLkeXlkNTg0
