### ISSUE TITLE
implement `_validate_local_name` and `_is_alpha_numeric` functions

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#17]
The `validate_local_ name` function validates that the handle being passed consists of just [a-z,0-9,_] and does not begin with an underscore and `_is_alpha_numeric` checks that the characters are all lowercased.

Here are some resources to help you with implementation:
- [validate_local_name implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/LensHandles.sol)
- [is_alpha_numeric implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/LensHandles.sol#L286)
- [Handle Documentation](https://docs.lens.xyz/docs/handle)

you are expected to:
- Implement the `_validate_local_name` and `_is_alpha_numeric` private functions respectively
- write the associated test for the implemented functions

Note that:
- your implementation, doesn't need to be an exact copy of lens implementation. Be flexible, and properly comment your codes.
- Ask questions in the working group, if lost or unsure of anything.

**Comment by mr-abims** [comment]
I will like to work on this

**Comment by codeWhizperer** [comment]
@mr-abims, any update on this? The feature Is needed to proceed with #15. Any progress on it?

**Comment by remybar** [comment]
Hi @Darlington02 !
If you are too busy to work on that task, I can handle it these days if you want 👍

**Comment by Darlington02** [comment]
Hey @remybar, sure give it a try!
