### ISSUE TITLE
implement handle registry `link` function

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#19]
The `link` function links a minted karst handle to a profile address.

Here are some resources to help you with implementation:
- [Lens implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/TokenHandleRegistry.sol#L57)
- [Handle Documentation](https://docs.lens.xyz/docs/handle)

you are expected to:
- Implement the `link` external and `_link` private functions respectively
- write the associated test for the implemented function

PS: Hub contract is yet to be implemented, so please implement but comment out any line which calls the Hub contract

Note that:
- your implementation, doesn't need to be an exact copy of lens implementation. Be flexible, and properly comment your codes.
- Ask questions in the working group, if lost or unsure of anything.

**Comment by CollinsC1O** [comment]
Hi @Darlington02 I will love to work on this

**Comment by kenkomu** [comment]
@codeWhizperer I will make a pull request tonight.

**Comment by kenkomu** [comment]
@codeWhizperer I have made a pull request as promised.

**Comment by Oshioke-Salaki** [comment]
If this is not being worked on, i'd like to take it up.
