### ISSUE TITLE
implement handle registry `resolve` function

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#21]
The `resolve` function returns the profile address linked to a handle NFT.

Here are some resources to help you with implementation:
- [Lens implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/TokenHandleRegistry.sol#L212)
- [Handle Documentation](https://docs.lens.xyz/docs/handle)

you are expected to:
- Implement the `resolve` function
- write the associated test for the implemented function

Note that:
- your implementation, doesn't need to be an exact copy of lens implementation. Be flexible, and properly comment your codes.
- Ask questions in the working group, if lost or unsure of anything.

**Comment by kenkomu** [comment]
Hello, can I work on this?

**Comment by codeWhizperer** [comment]
GM @MarvyNwaokobia , any update on this issue?

**Comment by od-hunter** [comment]
Can I be assigned this issue?

**Comment by mubarak23** [comment]
@MarvyNwaokobia are you still working on this.

**Comment by MarvyNwaokobia** [comment]
> @MarvyNwaokobia are you still working on this.

Yes I am
