### ISSUE TITLE
implement the handle registry `get_handle` function

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#22]
The `get_handle` function returns the handle linked to a profile address.

Here are some resources to help you with implementation:
- [Lens implementation](https://github.com/lens-protocol/core/blob/master/contracts/namespaces/TokenHandleRegistry.sol#L225)
- [Handle Documentation](https://docs.lens.xyz/docs/handle)

you are expected to:
- Implement the `get_handle` function
- write the associated test for the implemented function

Note that:
- your implementation, doesn't need to be an exact copy of lens implementation. Be flexible, and properly comment your codes.
- Ask questions in the working group, if lost or unsure of anything.

**Comment by kenkomu** [comment]
@Darlington02 can I work on this?

**Comment by Jemiiah** [comment]
I will create a draft PR soon @Darlington02
