### ISSUE TITLE
Implement ```mirror``` function in publication contract

### ISSUE THREAD

**Issue by codeWhizperer** [horuslabsio/karst-core#23]
Objective: Publish a ```mirror``` to a given profile and return the ```pub_id``` of the created publication.

Note: The implementation should ignore the ```_processMirrorIfNeeded``` as it is not a priority.

Resources
To aid in the implementation, refer to the following resources:

Mirror Feature Description: [Lens Protocol Docs - Mirror](https://docs.lens.xyz/docs/mirror)
Mirror Implementation: [GitHub - Lens Protocol](https://github.com/lens-protocol/core/blob/master/contracts/libraries/PublicationLib.sol#L116)

- Read through the existing implementation in the publication contract to familiarize yourself with the core functionalities.

 - Ask questions in the working group if you need help or clarification on anything.
 
 Note:
Write test for the implementation before creating a PR, and test should be in the `tests/test_publication.cairo` file

**Comment by kateberryd** [comment]
Hi @codeWhizperer I would like to work on this

**Comment by mubarak23** [comment]
@codeWhizperer can i work on this,

**Comment by mubarak23** [comment]
thank you
