### ISSUE TITLE
Implement ```quote``` function in publication contract

### ISSUE THREAD

**Issue by codeWhizperer** [horuslabsio/karst-core#24]
Objective: Publish a ```quote``` to a given profile and return the ```pub_id``` of the created publication.

Note: The implementation should ignore the ```_processMirrorIfNeeded``` as it is not a priority.

Resources
To aid in the implementation, refer to the following resources:

Quote Feature Description: [Lens Protocol Docs - Quote](https://docs.lens.xyz/docs/comment-copy)
Quote Implementation: [GitHub - Lens Protocol](https://github.com/lens-protocol/core/blob/master/contracts/libraries/PublicationLib.sol#L161)

- Read through the existing implementation in the publication contract to familiarize yourself with the core functionalities.

- Ask questions in the working group if you need help or clarification on anything.

Note:
Write test for the implementation before creating a PR, and test should be in the `tests/test_publication.cairo` file

**Comment by EjembiEmmanuel** [comment]
@codeWhizperer I'd love to work on this
