### ISSUE TITLE
Introduce ```_asReferencePubParams``` to enhance type Handling in ```_createReferencePublication```

### ISSUE THREAD

**Issue by codeWhizperer** [horuslabsio/karst-core#25]
The ```_asReferencePubParams``` function determines whether a given publication type should be treated as a quote or a comment. This function is crucial in formatting parameters passed to the ```_createReferencePublication``` function. 

Add  the ```_asReferencePubParams``` to ensure it effectively differentiates and processes parameters based on publication types:

[Quote Params Implementation](https://github.com/lens-protocol/core/blob/master/contracts/libraries/PublicationLib.sol#L226)

[Comment Params Implementation](https://github.com/lens-protocol/core/blob/master/contracts/libraries/PublicationLib.sol#L235)

Consider how ```_asReferencePubParams``` is utilized in ```_createReferencePublication```:

For comments: [Comment Implementation](https://github.com/lens-protocol/core/blob/master/contracts/libraries/PublicationLib.sol#L74)

For quotes: [Quote Implementation](https://github.com/lens-protocol/core/blob/master/contracts/libraries/PublicationLib.sol#L161)

- Feel free to make suggestions and reach out in the working group if you have any questions.

Note:
Write test for the implementation before creating a PR, and test should be in the `tests/test_publication.cairo` file

**Comment by Goodness5** [comment]
can you assign me this, i can work on this

**Comment by codeWhizperer** [comment]
@Goodness5 gm chief, this issue is paused for now. It will be available once #23, #24 is ready.

**Comment by Goodness5** [comment]
Alright sir 🫡🫡

**Comment by codeWhizperer** [comment]
checkout other issues ser

**Comment by mubarak23** [comment]
from the solidity implementation, we have two function with same name _asReferencePubParams, but the two function collect different argument i.e commentParams and quoteParams,

If we are implementing this, this mean we will have one function that collect one argument, then use a match pattern and return referencePubParams with type base on either commentParams or quoteParams was pass.

**Comment by codeWhizperer** [comment]
> from the solidity implementation, we have two function with same name _asReferencePubParams, but the two function collect different argument i.e commentParams and quoteParams,
> 
> If we are implementing this, this mean we will have one function that collect one argument, then use a match pattern and return referencePubParams with type base on either commentParams or quoteParams was pass.

@mubarak23 you're correct, wanna take on the issue, it's available?

**Comment by mubarak23** [comment]
> > from the solidity implementation, we have two function with same name _asReferencePubParams, but the two function collect different argument i.e commentParams and quoteParams,
> > If we are implementing this, this mean we will have one function that collect one argument, then use a match pattern and return referencePubParams with type base on either commentParams or quoteParams was pass.
> 
> @mubarak23, you're correct; do you want to work on the issue? it's available

Yes, kindly assign

**Comment by mubarak23** [comment]
> > > from the solidity implementation, we have two function with same name _asReferencePubParams, but the two function collect different argument i.e commentParams and quoteParams,
> > > If we are implementing this, this mean we will have one function that collect one argument, then use a match pattern and return referencePubParams with type base on either commentParams or quoteParams was pass.
> > 
> > 
> > @mubarak23, you're correct; do you want to work on the issue? it's available
> 
> Yes, kindly assign @codeWhizperer

**Comment by mubarak23** [comment]
inside comment and quote function, i need to change function argument i.e add a publicationType of value comment or quote which _asReferenceParam function will validate.


@codeWhizperer
