### ISSUE TITLE
Create An explainer tutorial on what ERC 6551 is and how Karst is leveraging it. 

### ISSUE THREAD

**Issue by eliashezron** [horuslabsio/karst-core#63]
EIP 6551 is an extention of ERC 721, We are leveraging this standard to allow users hold assets in their KARST accounts, This assets include tips that the users get from the posts aswell as other NFTS. 
For resources on eip 6551, 
1. The [EIP6551](https://eips.ethereum.org/EIPS/eip-6551)
2. checkout the [TBA](https://github.com/horuslabsio/TBA)
3. Medium [article](https://medium.com/@psocarde/eip-6551-the-future-of-non-fungible-tokens-a6f0651ab04d) by paul sorcade

**Comment by EjembiEmmanuel** [comment]
@codeWhizperer I'd love to work on this

**Comment by eliashezron** [comment]
> @eliashezron @codeWhizperer I'd love to work on this

take it on @EjembiEmmanuel

**Comment by gchimelu** [comment]
Hi @eliashezron, here from the Telegram group, taking it on 🤝

**Comment by od-hunter** [comment]
Hi @eliashezron Please can I be assigned also?

**Comment by od-hunter** [comment]
And what's the link to the Telegram group please? @eliashezron

**Comment by eliashezron** [comment]
> And what's the link to the Telegram group please? @eliashezron

join us on [telegram](https://t.me/+LbyQ2JDaQek2YTQ0)
