### ISSUE TITLE
Blog post style article introducing Karst on starknet and why its needed in the ecosystem

### ISSUE THREAD

**Issue by eliashezron** [horuslabsio/karst-core#64]
creatively narrate karst, highlighting the features that make us great and how we are leveraging starknet l2.

**Comment by Jemiiah** [comment]
I’d love to work on this issue @eliashezron

**Comment by DevPelz** [comment]
could i hop on this as a first contribution?

**Comment by gchimelu** [comment]
Hey, @eliashezron I'd love to work on this

**Comment by josephchimebuka** [comment]
I would like to contribute on this

**Comment by eliashezron** [comment]
> could i hop on this as a first contribution?

yes, definitely

**Comment by od-hunter** [comment]
Can I be assigned this also?

**Comment by josephchimebuka** [comment]
@Jemiiah Ok that makes sense what is your name on the telegram group?... so that I can send you a DM

**Comment by Jemiiah** [comment]
same as my GitHub handle
