### ISSUE TITLE
implement handle and follow `get_token_uri`

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#74]
Implement the `get_token_uri` methods in the handle and follow nft contracts.

Helper Links:

https://github.com/lens-protocol/core/tree/master/contracts/misc/token-uris

**Comment by mubarak23** [comment]
Kindly assign

**Comment by Dprof-in-tech** [comment]
Gm @Darlington02 , I would love to work on this issue if it has not been worked on

**Comment by EmmanuelAR** [comment]
Heyyyy @Darlington02 can i work on this?? im already work on some issues in this repo
