### ISSUE TITLE
Add tests for all emitted events in the `follownft.cairo` contract

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#92]
The `test_follownft` test file is currently missing test for all emitted events:
- Followed
- Unfollowed
- FollowerBlocked
- FollowerUnblocked

This issue requires you include tests for these events to ensure they are emitted as expected.

Resources:
https://foundry-rs.github.io/starknet-foundry/testing/testing-events.html

**Comment by adrianvrj** [comment]
hi, can I work on this?
