### ISSUE TITLE
Add tests for all events emitted in `handle_registry.cairo`

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#93]
The `test_handle_registry` test file is currently missing test for all emitted events:
- HandleLinked
- HandleUnlinked

This issue requires you include tests for these events to ensure they are emitted as expected.

Resources:
https://foundry-rs.github.io/starknet-foundry/testing/testing-events.html

**Comment by od-hunter** [comment]
I

**Comment by EmmanuelAR** [comment]
Hey

**Comment by EmmanuelAR** [comment]
Thanks for the opportunity, I will start asap @Darlington02

**Comment by EmmanuelAR** [comment]
Hey @Darlington02, heres the pr for the ticket, please let me know!

Thanks!
#108
