### ISSUE TITLE
update profile component tests

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#95]
The `test_profile` test file is currently missing test for the emitted event `CreatedProfile`. This issue requires you include tests for these events to ensure they are emitted as expected.

Also currently the profile tests do not check to confirm that a follow nft contract is deployed when a profile is created. add an extra test case to check that this happens.

Resources:
https://foundry-rs.github.io/starknet-foundry/testing/testing-events.html

**Comment by manlikeHB** [comment]
@Darlington02  Can i work on this? I've had experience writing test cairo in previous ODHacks.
