### ISSUE TITLE
Add tests for emitted events in `publication.cairo`

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#96]
The `test_publication` test file is currently missing test for all emitted events:
- Post
- CommentCreated
- MirrorCreated
- QuoteCreated

This issue requires you include tests for these events to ensure they are emitted as expected.

Resources:
https://foundry-rs.github.io/starknet-foundry/testing/testing-events.html

**Comment by Oshioke-Salaki** [comment]
Please can I do this?

**Comment by Gerson2102** [comment]
**Tell us about your background and how it can be leveraged:**

I'm a junior software developer with contributions to several OnlyDust projects, including Madara, Cairo native, kakarot-rpc, and giza. Given that Cairo is quite similar to Rust and all the projects where i contributed are in Rust, I know the Cairo syntax. You can check my OD profile here: [https://app.onlydust.com/](https://app.onlydust.com/)

**How would you approach the problem?**

I will approach the problem by first reviewing the resources shared with me. I will search for similar code within the project that could assist me. Additionally, I will conduct my own research using the Cairo book and examining other related projects. If I encounter significant challenges, I will seek assistance from the Telegram groups.

**Comment by KingFRANKHOOD** [comment]
I'm a new cairo developer looking to get my hand dirty with some tasks and I'll love to try this task. My previous experriences only includes participating in the last hackathon with a team of 4 where i wrote my first smart contract
