### ISSUE TITLE
more `follownft` tests

### ISSUE THREAD

**Issue by Darlington02** [horuslabsio/karst-core#97]
This issue requires you to:

1. Write a test case for the [`is_blocked`](https://github.com/horuslabsio/karst-core/blob/main/src/follownft/follownft.cairo#L287) method in the `follownft` contract.
2. Write a test case that checks that following mints a new follow nft to the follower, and unfollowing burns the follow nft.

**Comment by od-hunter** [comment]
Can I be assigned this please?

**Comment by od-hunter** [comment]
Thank you sir🙏🏾
I’ll start work asap!
